[default]
address = "127.0.0.1"
port = 8000
workers = 16
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="

[default.limits]
forms = "64 kB"
file = "5 MiB" # 1x value
data-form = "10 MiB" # 2x value - MAKE IT AT LEAST 2 times bigger than file


